_BASE_: "../Base-RCNN-FPN-OPENDET_MTSD_2x_size.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 402
    NUM_KNOWN_CLASSES: 230
DATASETS:
  TRAIN: ('MTSD_SPCLUST_t1_t2t3_train', )
  TEST: ('MTSD_SPCLUST_t1_t2t3_test', )
SOLVER:
  STEPS: (38000, 47000)
  MAX_ITER: 51000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 230
  EVAL_UNKNOWN: True
  EVAL_TARGET_CLS: 400