_BASE_: "../Base-RCNN-FPN-OPENDET_CUB200.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 200 # remove unk class
    NUM_KNOWN_CLASSES: 150
  ROI_BOX_HEAD:
    OUTPUT_LAYERS: "OpenDetFastRCNNOutputLayers_MINUS"
DATASETS:
  TRAIN: ('CUB200_random_t3_train', )
  TEST: ('CUB200_random_t3_test', )
SOLVER:
  STEPS: (15000, 18200)
  MAX_ITER: 20000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 150
  EVAL_UNKNOWN: True
  EVAL_TARGET_CLS: 200
RATIO_UD:
  UNK_RATIO: 3.0
  AFTER_NMS: False
ICLOSS:
  WEIGHT: 0.0