_BASE_: "../../Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 6
    NUM_KNOWN_CLASSES: 6
  ROI_BOX_HEAD:
    OUTPUT_LAYERS: "OpenDetFastRCNNOutputLayers_MINUS"
DATASETS:
  TRAIN: ('seed100_vehicle_t4_openimages_v6_train', )
  TEST: ('seed100_vehicle_t4_openimages_v6_test', )
SOLVER:
  STEPS: (4500, 5500)
  MAX_ITER: 6000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 6
  EVAL_UNKNOWN: True
  EVAL_TARGET_CLS: 24
RATIO_UD:
  UNK_RATIO: 15.0
  AFTER_NMS: False
  COMPARE_BG: False
ICLOSS:
  WEIGHT: 0.0